"""Single registry for every standalone JSON Schema published by the runtime."""

from full_view_agent.domain.models import (
    AgentEvent,
    AgentMessage,
    AgentRun,
    AgentSession,
    AreaCandidatesResult,
    AuthContext,
    ContractModel,
    EventFinishRateTable,
    Evidence,
    FrontendCommand,
    FrontendCommandReceipt,
    GetObjectProfileInput,
    HousingAreaGroupTable,
    HousingLeaseTypeTable,
    InternalToolManifest,
    ModelToolDescriptor,
    ObjectProfileResult,
    PendingInputRequest,
    PolicyDecision,
    PopulationMetricTable,
    QueryEventMetricsInput,
    QueryHousingMetricsInput,
    QueryPopulationMetricsInput,
    ResolveAreaInput,
    ResultMetadata,
    RunCreateRequest,
    RunInputBody,
    Steer,
    TableDataResult,
    ToolResult,
)

SCHEMA_MODELS: dict[str, type[ContractModel]] = {
    "agent/run-create-request.schema.json": RunCreateRequest,
    "agent/run-input-body.schema.json": RunInputBody,
    "agent/pending-input-request.schema.json": PendingInputRequest,
    "agent/agent-session.schema.json": AgentSession,
    "agent/agent-run.schema.json": AgentRun,
    "agent/agent-event.schema.json": AgentEvent,
    "agent/agent-message.schema.json": AgentMessage,
    "agent/steer.schema.json": Steer,
    "frontend/frontend-command.schema.json": FrontendCommand,
    "frontend/frontend-command-receipt.schema.json": FrontendCommandReceipt,
    "common/auth-context.schema.json": AuthContext,
    "policy/policy-decision.schema.json": PolicyDecision,
    "tools/internal-tool-manifest.schema.json": InternalToolManifest,
    "tools/model-tool-descriptor.schema.json": ModelToolDescriptor,
    "tools/resolve-area-input.schema.json": ResolveAreaInput,
    "tools/query-event-metrics-input.schema.json": QueryEventMetricsInput,
    "tools/query-housing-metrics-input.schema.json": QueryHousingMetricsInput,
    "tools/query-population-metrics-input.schema.json": QueryPopulationMetricsInput,
    "tools/get-object-profile-input.schema.json": GetObjectProfileInput,
    "tools/tool-result.schema.json": ToolResult,
    "data/area-candidates.schema.json": AreaCandidatesResult,
    "data/object-profile.schema.json": ObjectProfileResult,
    "data/table-data-result.schema.json": TableDataResult,
    "data/result-metadata.schema.json": ResultMetadata,
    "data/evidence.schema.json": Evidence,
    "data/tool-specific/population-metric-table.schema.json": PopulationMetricTable,
    "data/tool-specific/housing-lease-type-table.schema.json": HousingLeaseTypeTable,
    "data/tool-specific/housing-area-group-table.schema.json": HousingAreaGroupTable,
    "data/tool-specific/event-finish-rate-table.schema.json": EventFinishRateTable,
}
